// frontend/src/components/TaskCreationDialog.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { toast } from 'svelte-sonner';
  import { api } from '@/lib/apiClient';
  import type { NotifyBehavior, TaskTemplate } from '@/lib/types';

  import Dialog from './ui/Dialog.svelte';
  import Button from './ui/Button.svelte';
  import Input from './ui/Input.svelte';
  import Label from './ui/Label.svelte';
  import Textarea from './ui/Textarea.svelte';
  import Select from './ui/Select.svelte';
  import { Loader2, Info, Sparkles } from 'lucide-svelte';

  export let open = false;
  export let onOpenChange: (open: boolean) => void;
  export let onTaskCreated: () => void;

  const SCHEDULE_OPTIONS = [
    { value: '*/30 * * * *', label: 'Every 30 minutes' },
    { value: '0 */6 * * *', label: 'Every 6 hours' },
    { value: '0 9 * * *', label: 'Every day at 9:00 AM' },
    { value: '0 12 * * *', label: 'Every day at noon' },
    { value: '0 8 * * 1', label: 'Every Monday at 8:00 AM' },
    { value: '0 0 * * 0', label: 'Every Sunday at midnight' },
  ];

  let templates: TaskTemplate[] = [];
  let selectedTemplateId = 'none';
  let name = '';
  let searchQuery = '';
  let conditionDescription = '';
  let schedule = '0 9 * * *';
  let notifyBehavior: NotifyBehavior = 'track_state';
  let isLoading = false;
  let error = '';

  onMount(async () => {
    try {
      const data = await api.getTemplates();
      templates = data;
    } catch (err) {
      console.error('Failed to load templates:', err);
    }
  });

  $: if (selectedTemplateId && selectedTemplateId !== 'none') {
    const template = templates.find((t) => t.id === selectedTemplateId);
    if (template) {
      name = template.name;
      searchQuery = template.search_query;
      conditionDescription = template.condition_description;
      schedule = template.schedule;
      notifyBehavior = template.notify_behavior;
    }
  }

  async function handleSubmit(e: Event) {
    e.preventDefault();
    error = '';
    isLoading = true;

    try {
      await api.createTask({
        name,
        search_query: searchQuery,
        condition_description: conditionDescription,
        schedule,
        notify_behavior: notifyBehavior,
        executor_type: 'llm_grounded_search',
        config: {
          model: 'gemini-2.0-flash-exp',
          search_provider: 'google',
        },
        is_active: true,
      });

      toast.success('Task created successfully');

      // Reset form
      selectedTemplateId = 'none';
      name = '';
      searchQuery = '';
      conditionDescription = '';
      schedule = '0 9 * * *';
      notifyBehavior = 'track_state';

      onTaskCreated();
      onOpenChange(false);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to create task';
      error = errorMessage;
      toast.error(errorMessage);
    } finally {
      isLoading = false;
    }
  }

  // Group templates by category
  $: groupedTemplates = templates.reduce((acc, template) => {
    if (!acc[template.category]) {
      acc[template.category] = [];
    }
    acc[template.category].push(template);
    return acc;
  }, {} as Record<string, TaskTemplate[]>);
</script>

<Dialog {open} {onOpenChange}>
  <div class="space-y-4">
    <div>
      <h2 class="text-lg font-semibold">Create Monitoring Task</h2>
      <p class="text-sm text-muted-foreground">
        Set up AI-powered monitoring for any web-based information
      </p>
    </div>

    <form on:submit={handleSubmit} class="space-y-6">
      {#if templates.length > 0}
        <div class="space-y-2 pb-4 border-b">
          <Label htmlFor="template" class="flex items-center gap-2">
            <Sparkles class="h-4 w-4 text-purple-500" />
            Start from Template (Optional)
          </Label>
          <Select id="template" bind:value={selectedTemplateId}>
            <option value="none">Create from scratch</option>
            {#each Object.entries(groupedTemplates) as [category, categoryTemplates]}
              <optgroup label={category}>
                {#each categoryTemplates as template}
                  <option value={template.id}>
                    {template.icon ? `${template.icon} ` : ''}{template.name}
                  </option>
                {/each}
              </optgroup>
            {/each}
          </Select>
          <p class="text-xs text-muted-foreground">
            Select a template to auto-fill the form, then customize as needed
          </p>
        </div>
      {/if}

      <div class="space-y-2">
        <Label htmlFor="name">Task Name</Label>
        <Input
          id="name"
          placeholder="e.g., iPhone 16 Release Date"
          bind:value={name}
          required
          disabled={isLoading}
        />
        <p class="text-xs text-muted-foreground">
          A descriptive name to identify this monitoring task
        </p>
      </div>

      <div class="space-y-2">
        <Label htmlFor="searchQuery">Search Query</Label>
        <Textarea
          id="searchQuery"
          placeholder="e.g., When is the next iPhone being announced?"
          bind:value={searchQuery}
          required
          disabled={isLoading}
          rows={3}
        />
        <p class="text-xs text-muted-foreground">
          What should we search for? Be specific and use natural language.
        </p>
      </div>

      <div class="space-y-2">
        <Label htmlFor="condition">Trigger Condition</Label>
        <Textarea
          id="condition"
          placeholder="e.g., A specific release date is announced"
          bind:value={conditionDescription}
          required
          disabled={isLoading}
          rows={2}
        />
        <p class="text-xs text-muted-foreground">
          When should we notify you? Describe the condition that matters to you.
        </p>
      </div>

      <div class="space-y-2">
        <Label htmlFor="schedule">Check Frequency</Label>
        <Select id="schedule" bind:value={schedule} disabled={isLoading}>
          {#each SCHEDULE_OPTIONS as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </Select>
        <p class="text-xs text-muted-foreground">
          How often should we check for updates?
        </p>
      </div>

      <div class="space-y-2">
        <Label htmlFor="notifyBehavior">Notification Behavior</Label>
        <Select id="notifyBehavior" bind:value={notifyBehavior} disabled={isLoading}>
          <option value="once">Notify Once (stop after first match)</option>
          <option value="always">Always Notify (every time condition is met)</option>
          <option value="track_state">Track State Changes (notify when information changes)</option>
        </Select>
        <p class="text-xs text-muted-foreground">
          How should we handle repeated notifications?
        </p>
      </div>

      <div class="flex items-center gap-2 p-4 rounded-lg border bg-card">
        <Info class="h-4 w-4 shrink-0" />
        <p class="text-sm">
          The AI will search the web, analyze results, and notify you when your condition is met. All findings include source links for verification.
        </p>
      </div>

      {#if error}
        <div class="p-4 rounded-lg border border-destructive bg-destructive/10 text-destructive text-sm">
          {error}
        </div>
      {/if}

      <div class="flex gap-2 justify-end">
        <Button type="button" variant="outline" on:click={() => onOpenChange(false)} disabled={isLoading}>
          Cancel
        </Button>
        <Button type="submit" disabled={isLoading}>
          {#if isLoading}
            <Loader2 class="mr-2 h-4 w-4 animate-spin" />
          {/if}
          Create Task
        </Button>
      </div>
    </form>
  </div>
</Dialog>

// frontend/mock/components/tasks/TaskCreationDialog.tsx
import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "../ui/dialog";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { Textarea } from "../ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../ui/select";
import { NotifyBehavior } from "../../types";
import { tasksApi } from "../../lib/mockApi";
import { Loader2, Info } from "lucide-react";
import { Alert } from "../ui/alert";

interface TaskCreationDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onTaskCreated: () => void;
}

const SCHEDULE_OPTIONS = [
  { value: "*/30 * * * *", label: "Every 30 minutes" },
  { value: "0 */6 * * *", label: "Every 6 hours" },
  { value: "0 9 * * *", label: "Every day at 9:00 AM" },
  { value: "0 12 * * *", label: "Every day at noon" },
  { value: "0 8 * * 1", label: "Every Monday at 8:00 AM" },
  { value: "0 0 * * 0", label: "Every Sunday at midnight" },
];

export const TaskCreationDialog: React.FC<TaskCreationDialogProps> = ({
  open,
  onOpenChange,
  onTaskCreated,
}) => {
  const [name, setName] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const [conditionDescription, setConditionDescription] = useState("");
  const [schedule, setSchedule] = useState("0 9 * * *");
  const [notifyBehavior, setNotifyBehavior] = useState<NotifyBehavior>("track_state");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setIsLoading(true);

    try {
      await tasksApi.createTask({
        name,
        search_query: searchQuery,
        condition_description: conditionDescription,
        schedule,
        notify_behavior: notifyBehavior,
        executor_type: "llm_grounded_search",
        is_active: true,
      });

      // Reset form
      setName("");
      setSearchQuery("");
      setConditionDescription("");
      setSchedule("0 9 * * *");
      setNotifyBehavior("track_state");

      onTaskCreated();
      onOpenChange(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create task");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create Monitoring Task</DialogTitle>
          <DialogDescription>
            Set up AI-powered monitoring for any web-based information
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="name">Task Name</Label>
            <Input
              id="name"
              placeholder="e.g., iPhone 16 Release Date"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              disabled={isLoading}
            />
            <p className="text-xs text-muted-foreground">
              A descriptive name to identify this monitoring task
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="searchQuery">Search Query</Label>
            <Textarea
              id="searchQuery"
              placeholder="e.g., When is the next iPhone being announced?"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              required
              disabled={isLoading}
              rows={3}
            />
            <p className="text-xs text-muted-foreground">
              What should we search for? Be specific and use natural language.
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="condition">Trigger Condition</Label>
            <Textarea
              id="condition"
              placeholder="e.g., A specific release date is announced"
              value={conditionDescription}
              onChange={(e) => setConditionDescription(e.target.value)}
              required
              disabled={isLoading}
              rows={2}
            />
            <p className="text-xs text-muted-foreground">
              When should we notify you? Describe the condition that matters to you.
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="schedule">Check Frequency</Label>
            <Select value={schedule} onValueChange={setSchedule} disabled={isLoading}>
              <SelectTrigger id="schedule">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {SCHEDULE_OPTIONS.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">
              How often should we check for updates?
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="notifyBehavior">Notification Behavior</Label>
            <Select
              value={notifyBehavior}
              onValueChange={(value) => setNotifyBehavior(value as NotifyBehavior)}
              disabled={isLoading}
            >
              <SelectTrigger id="notifyBehavior">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="once">
                  Notify Once (stop after first match)
                </SelectItem>
                <SelectItem value="always">
                  Always Notify (every time condition is met)
                </SelectItem>
                <SelectItem value="track_state">
                  Track State Changes (notify when information changes)
                </SelectItem>
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">
              How should we handle repeated notifications?
            </p>
          </div>

          <Alert>
            <Info className="h-4 w-4" />
            <div className="ml-2">
              <p className="text-sm">
                The AI will search the web, analyze results, and notify you when your
                condition is met. All findings include source links for verification.
              </p>
            </div>
          </Alert>

          {error && <Alert variant="destructive">{error}</Alert>}

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isLoading}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isLoading}>
              {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Create Task
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};
