// frontend/src/components/ExecutionTimeline.tsx
import React from "react";
import ReactMarkdown from "react-markdown";
import { TaskExecution } from "@/types";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { GroundingSourceList } from "@/components/ui/GroundingSourceList";
import {
  CheckCircle2,
  XCircle,
  Clock,
  AlertCircle,
} from "lucide-react";

interface ExecutionTimelineProps {
  executions: TaskExecution[];
  highlightNotifications?: boolean;
}

export const ExecutionTimeline: React.FC<ExecutionTimelineProps> = ({
  executions,
  highlightNotifications = false,
}) => {
  if (executions.length === 0) {
    return (
      <div className="text-center py-12">
        <Clock className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
        <h3 className="mb-2">No executions yet</h3>
        <p className="text-muted-foreground">
          This task hasn't been executed yet. It will run according to its schedule.
        </p>
      </div>
    );
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "success":
        return <CheckCircle2 className="h-5 w-5 text-green-500" />;
      case "failed":
        return <XCircle className="h-5 w-5 text-red-500" />;
      default:
        return <Clock className="h-5 w-5 text-yellow-500" />;
    }
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    }).format(date);
  };

  return (
    <div className="space-y-4">
      {executions.map((execution) => (
        <Card
          key={execution.id}
          className={
            highlightNotifications && execution.condition_met
              ? "border-2 border-emerald-500 bg-emerald-50/30"
              : "border-2"
          }
        >
          <div className="p-4">
            <div className="flex items-start gap-4">
              <div className="shrink-0 mt-1">{getStatusIcon(execution.status)}</div>

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2">
                  <Badge
                    variant={
                      execution.status === "success"
                        ? "default"
                        : execution.status === "failed"
                        ? "destructive"
                        : "secondary"
                    }
                  >
                    {execution.status}
                  </Badge>

                  {execution.condition_met && (
                    <Badge variant="default">
                      <AlertCircle className="mr-1 h-3 w-3" />
                      Condition Met
                    </Badge>
                  )}

                  <span className="text-sm text-muted-foreground ml-auto">
                    {formatDate(execution.started_at)}
                  </span>
                </div>

                {execution.change_summary && (
                  <div className="p-3 bg-zinc-50 border-2 border-zinc-100 mb-3">
                    <p className="text-sm">
                      <span className="font-mono text-[10px] uppercase text-zinc-400 tracking-wider block mb-1">What Changed</span>
                      {execution.change_summary}
                    </p>
                  </div>
                )}

                {execution.result?.answer && (
                  <div className="mb-3 p-4 bg-zinc-50 border-2 border-zinc-100">
                    <p className="text-[10px] font-mono uppercase text-zinc-400 tracking-wider mb-3">Answer</p>
                    <div className="text-sm prose prose-sm max-w-none">
                      <ReactMarkdown
                        components={{
                          p: ({ children }) => <p className="mb-3 leading-relaxed text-zinc-900">{children}</p>,
                          ul: ({ children }) => <ul className="list-disc pl-5 mb-3 space-y-1.5">{children}</ul>,
                          ol: ({ children }) => <ol className="list-decimal pl-5 mb-3 space-y-1.5">{children}</ol>,
                          li: ({ children }) => <li className="text-sm leading-relaxed text-zinc-700">{children}</li>,
                          strong: ({ children }) => <strong className="font-bold text-zinc-900">{children}</strong>,
                          h1: ({ children }) => <h1 className="text-xl font-grotesk font-bold mb-3 mt-4 text-zinc-900">{children}</h1>,
                          h2: ({ children }) => <h2 className="text-lg font-grotesk font-bold mb-2 mt-3 text-zinc-900">{children}</h2>,
                          h3: ({ children }) => <h3 className="text-base font-grotesk font-bold mb-2 mt-2 text-zinc-900">{children}</h3>,
                        }}
                      >
                        {execution.result.answer}
                      </ReactMarkdown>
                    </div>
                  </div>
                )}

                {execution.result?.current_state && (
                  <div className="mb-3 p-4 bg-zinc-50 border-2 border-zinc-100">
                    <p className="text-[10px] font-mono uppercase text-zinc-400 tracking-wider mb-3">Current State</p>
                    <div className="text-sm space-y-3">
                      {Object.entries(execution.result.current_state).map(
                        ([key, value]) => (
                          <div key={key} className="flex flex-col gap-1">
                            <span className="font-mono text-xs text-zinc-900 font-bold">
                              {key.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())}
                            </span>
                            {Array.isArray(value) ? (
                              value.length > 3 ? (
                                <span className="text-sm text-zinc-600">{value.slice(0, 3).join(", ")} and {value.length - 3} more</span>
                              ) : (
                                <span className="text-sm text-zinc-600">{value.join(", ")}</span>
                              )
                            ) : typeof value === "object" && value !== null ? (
                              <pre className="text-xs mt-1 p-3 bg-zinc-900 text-zinc-300 border border-zinc-800 overflow-x-auto font-mono">
                                {JSON.stringify(value, null, 2)}
                              </pre>
                            ) : (
                              <span className="text-sm text-zinc-600">{String(value)}</span>
                            )}
                          </div>
                        )
                      )}
                    </div>
                  </div>
                )}

                <GroundingSourceList
                  sources={execution.grounding_sources}
                  title="Grounding Sources:"
                />

                {execution.error_message && (
                  <div className="p-4 bg-red-50 border-2 border-red-200">
                    <p className="text-[10px] font-mono uppercase text-red-400 tracking-wider mb-2">Error</p>
                    <p className="text-sm text-red-600 font-mono">
                      {execution.error_message}
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </Card>
      ))}
    </div>
  );
};

// frontend/src/components/ExecutionTimeline.svelte
<script lang="ts">
  import type { TaskExecution } from '@/lib/types';
  import Badge from './ui/Badge.svelte';
  import Card from './ui/Card.svelte';
  import { CheckCircle2, XCircle, Clock, ExternalLink, AlertCircle } from 'lucide-svelte';

  export let executions: TaskExecution[];
  export let highlightNotifications = false;

  function getStatusIcon(status: string) {
    switch (status) {
      case 'success':
        return CheckCircle2;
      case 'failed':
        return XCircle;
      default:
        return Clock;
    }
  }

  function getStatusColor(status: string) {
    switch (status) {
      case 'success':
        return 'text-green-500';
      case 'failed':
        return 'text-red-500';
      default:
        return 'text-yellow-500';
    }
  }

  function formatDate(dateStr: string) {
    const date = new Date(dateStr);
    return new Intl.DateTimeFormat('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    }).format(date);
  }

  function formatValue(value: any): string {
    if (Array.isArray(value)) {
      return value.length > 3
        ? `${value.slice(0, 3).join(', ')} and ${value.length - 3} more`
        : value.join(', ');
    }
    if (typeof value === 'object' && value !== null) {
      return JSON.stringify(value, null, 2);
    }
    return String(value);
  }

  function formatKey(key: string): string {
    return key
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (l) => l.toUpperCase());
  }
</script>

{#if executions.length === 0}
  <div class="text-center py-12">
    <Clock class="h-12 w-12 mx-auto text-muted-foreground mb-4" />
    <h3 class="text-lg font-semibold mb-2">No executions yet</h3>
    <p class="text-muted-foreground">
      This task hasn't been executed yet. It will run according to its schedule.
    </p>
  </div>
{:else}
  <div class="space-y-4">
    {#each executions as execution (execution.id)}
      <Card
        class={highlightNotifications && execution.condition_met
          ? 'border-primary bg-primary/5'
          : ''}
      >
        <div class="p-4">
          <div class="flex items-start gap-4">
            <div class="shrink-0 mt-1">
              <svelte:component
                this={getStatusIcon(execution.status)}
                class="h-5 w-5 {getStatusColor(execution.status)}"
              />
            </div>

            <div class="flex-1 min-w-0">
              <div class="flex items-center gap-2 mb-2 flex-wrap">
                <Badge
                  variant={execution.status === 'success'
                    ? 'default'
                    : execution.status === 'failed'
                    ? 'destructive'
                    : 'secondary'}
                >
                  {execution.status}
                </Badge>

                {#if execution.condition_met}
                  <Badge variant="default">
                    <AlertCircle class="mr-1 h-3 w-3" />
                    Condition Met
                  </Badge>
                {/if}

                <span class="text-sm text-muted-foreground ml-auto">
                  {formatDate(execution.started_at)}
                </span>
              </div>

              {#if execution.change_summary}
                <div class="p-3 bg-muted rounded-md mb-3">
                  <p class="text-sm">
                    <span class="font-medium">What Changed: </span>
                    {execution.change_summary}
                  </p>
                </div>
              {/if}

              {#if execution.result?.answer}
                <div class="mb-3">
                  <div class="text-sm prose prose-sm max-w-none">
                    {@html execution.result.answer.replace(/\n/g, '<br>')}
                  </div>
                </div>
              {/if}

              {#if execution.result?.current_state}
                <div class="mb-3 p-3 bg-muted rounded-md">
                  <p class="text-sm font-medium mb-3">Current State:</p>
                  <div class="text-sm text-muted-foreground space-y-2">
                    {#each Object.entries(execution.result.current_state) as [key, value]}
                      <div>
                        <span class="font-medium text-foreground">
                          {formatKey(key)}:
                        </span>{' '}
                        <span class="text-xs">{formatValue(value)}</span>
                      </div>
                    {/each}
                  </div>
                </div>
              {/if}

              {#if execution.grounding_sources.length > 0}
                <div>
                  <p class="text-sm mb-2">Grounding Sources:</p>
                  <div class="space-y-2">
                    {#each execution.grounding_sources as source}
                      <a
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        class="flex items-start gap-2 p-2 rounded-md hover:bg-muted transition-colors group"
                      >
                        <ExternalLink class="h-4 w-4 shrink-0 mt-0.5 text-muted-foreground group-hover:text-primary" />
                        <div class="flex-1 min-w-0">
                          <p class="text-sm group-hover:text-primary truncate">
                            {source.title}
                          </p>
                          <p class="text-xs text-muted-foreground truncate">
                            {source.url}
                          </p>
                        </div>
                      </a>
                    {/each}
                  </div>
                </div>
              {/if}

              {#if execution.error_message}
                <div class="p-3 bg-destructive/10 border border-destructive/20 rounded-md">
                  <p class="text-sm text-destructive">
                    <span class="font-medium">Error: </span>
                    {execution.error_message}
                  </p>
                </div>
              {/if}
            </div>
          </div>
        </div>
      </Card>
    {/each}
  </div>
{/if}
