// frontend/mock/components/layout/Header.tsx
import React from "react";
import { Button } from "../ui/button";
import { useAuth } from "../../contexts/AuthContext";
import { Bell, LogOut, User } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "../ui/dropdown-menu";

export const Header: React.FC = () => {
  const { user, logout } = useAuth();

  return (
    <header className="border-b">
      <div className="container mx-auto px-4 h-16 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Bell className="h-6 w-6 text-primary" />
          <h2>Torale</h2>
        </div>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon">
              <User className="h-5 w-5" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <div className="px-2 py-1.5">
              <p className="text-sm">{user?.email}</p>
            </div>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={logout}>
              <LogOut className="mr-2 h-4 w-4" />
              Sign Out
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
};

// frontend/src/components/Header.svelte
<script lang="ts">
  import { Bell } from 'lucide-svelte';
  import { clerkUser, clerk } from '@/lib/clerk';
  import { onMount } from 'svelte';

  let userButtonMounted = false;

  onMount(() => {
    setTimeout(() => {
      const userButtonElement = document.getElementById('clerk-user-button');
      if (userButtonElement && !userButtonMounted) {
        clerk.mountUserButton(userButtonElement);
        userButtonMounted = true;
      }
    }, 100);
  });
</script>

<header class="border-b">
  <div class="container mx-auto px-4 h-16 flex items-center justify-between">
    <div class="flex items-center gap-2">
      <Bell class="h-6 w-6 text-primary" />
      <h2 class="text-xl font-semibold">Torale</h2>
    </div>

    <div class="flex items-center gap-4">
      {#if $clerkUser}
        <span class="text-sm text-muted-foreground hidden sm:inline">
          {$clerkUser.primaryEmailAddress?.emailAddress}
        </span>
      {/if}
      <div id="clerk-user-button"></div>
    </div>
  </div>
</header>
