// frontend/mock/components/tasks/TaskDetail.tsx
import React, { useState, useEffect } from "react";
import { Task, TaskExecution } from "../../types";
import { tasksApi, executionsApi, parseCron } from "../../lib/mockApi";
import { Button } from "../ui/button";
import { Badge } from "../ui/badge";
import { Switch } from "../ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { Card, CardHeader, CardContent } from "../ui/card";
import { ExecutionTimeline } from "./ExecutionTimeline";
import { StateComparison } from "./StateComparison";
import {
  ArrowLeft,
  Clock,
  Search,
  Bell,
  Play,
  Loader2,
  Settings,
  Trash2,
} from "lucide-react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "../ui/alert-dialog";

interface TaskDetailProps {
  taskId: string;
  onBack: () => void;
  onDeleted: () => void;
}

export const TaskDetail: React.FC<TaskDetailProps> = ({
  taskId,
  onBack,
  onDeleted,
}) => {
  const [task, setTask] = useState<Task | null>(null);
  const [executions, setExecutions] = useState<TaskExecution[]>([]);
  const [notifications, setNotifications] = useState<TaskExecution[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isExecuting, setIsExecuting] = useState(false);
  const [activeTab, setActiveTab] = useState("executions");

  const loadData = async () => {
    setIsLoading(true);
    try {
      const [taskData, executionsData, notificationsData] = await Promise.all([
        tasksApi.getTask(taskId),
        executionsApi.getExecutions(taskId),
        executionsApi.getNotifications(taskId),
      ]);
      setTask(taskData);
      setExecutions(executionsData);
      setNotifications(notificationsData);
    } catch (error) {
      console.error("Failed to load task details:", error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [taskId]);

  const handleToggle = async () => {
    if (!task) return;
    try {
      await tasksApi.updateTask(taskId, { is_active: !task.is_active });
      await loadData();
    } catch (error) {
      console.error("Failed to toggle task:", error);
    }
  };

  const handleExecute = async () => {
    setIsExecuting(true);
    try {
      await tasksApi.executeTask(taskId);
      await loadData();
    } catch (error) {
      console.error("Failed to execute task:", error);
    } finally {
      setIsExecuting(false);
    }
  };

  const handleDelete = async () => {
    try {
      await tasksApi.deleteTask(taskId);
      onDeleted();
    } catch (error) {
      console.error("Failed to delete task:", error);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!task) {
    return (
      <div className="text-center py-12">
        <p className="text-muted-foreground mb-4">Task not found</p>
        <Button onClick={onBack}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Dashboard
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div className="flex items-start gap-4 flex-1">
          <Button variant="ghost" size="icon" onClick={onBack}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <h1>{task.name}</h1>
              {task.condition_met && <Badge variant="default">Triggered</Badge>}
              {!task.is_active && <Badge variant="secondary">Paused</Badge>}
            </div>
            <p className="text-muted-foreground">{task.search_query}</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            onClick={handleExecute}
            disabled={isExecuting}
          >
            {isExecuting ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Play className="mr-2 h-4 w-4" />
            )}
            Run Now
          </Button>

          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="outline" size="icon">
                <Trash2 className="h-4 w-4" />
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Delete Task</AlertDialogTitle>
                <AlertDialogDescription>
                  Are you sure you want to delete "{task.name}"? This action cannot be
                  undone. All execution history will be permanently deleted.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={handleDelete}>Delete</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Clock className="h-4 w-4" />
              <p>Schedule</p>
            </div>
          </CardHeader>
          <CardContent>
            <p>{parseCron(task.schedule)}</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Search className="h-4 w-4" />
              <p>Trigger Condition</p>
            </div>
          </CardHeader>
          <CardContent>
            <p>{task.condition_description}</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Bell className="h-4 w-4" />
              <p>Notification Behavior</p>
            </div>
          </CardHeader>
          <CardContent>
            <p className="capitalize mb-3">{task.notify_behavior.replace("_", " ")}</p>
            <div className="flex items-center gap-2">
              <Switch checked={task.is_active} onCheckedChange={handleToggle} />
              <span className="text-sm text-muted-foreground">
                {task.is_active ? "Active" : "Paused"}
              </span>
            </div>
          </CardContent>
        </Card>
      </div>

      {task.last_known_state && (
        <Card>
          <CardHeader>
            <h3>Last Known State</h3>
          </CardHeader>
          <CardContent>
            <div className="text-sm space-y-2">
              {Object.entries(task.last_known_state).map(([key, value]) => (
                <div key={key} className="flex items-start gap-2">
                  <span className="font-medium min-w-[150px]">{key}:</span>
                  <span className="text-muted-foreground">
                    {typeof value === "object" ? JSON.stringify(value, null, 2) : String(value)}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="executions">
            All Executions ({executions.length})
          </TabsTrigger>
          <TabsTrigger value="notifications">
            Notifications ({notifications.length})
          </TabsTrigger>
          <TabsTrigger value="changes">State Changes</TabsTrigger>
        </TabsList>

        <TabsContent value="executions" className="mt-6">
          <ExecutionTimeline executions={executions} />
        </TabsContent>

        <TabsContent value="notifications" className="mt-6">
          <ExecutionTimeline
            executions={notifications}
            highlightNotifications={true}
          />
        </TabsContent>

        <TabsContent value="changes" className="mt-6">
          <StateComparison executions={executions} />
        </TabsContent>
      </Tabs>
    </div>
  );
};

// frontend/src/components/TaskDetail.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { toast } from 'svelte-sonner';
  import { api } from '@/lib/apiClient';
  import type { Task, TaskExecution } from '@/lib/types';

  import Button from './ui/button.svelte';
  import Badge from './ui/badge.svelte';
  import Switch from './ui/switch.svelte';
  import Card from './ui/card.svelte';
  import Loader from './Loader.svelte';
  import ExecutionTimeline from './ExecutionTimeline.svelte';
  import StateComparison from './StateComparison.svelte';
  import { ArrowLeft, Clock, Search, Bell, Play, Loader2 as LoaderIcon, Trash2 } from 'lucide-svelte';

  export let taskId: string;
  export let onBack: () => void;
  export let onDeleted: () => void;


  let task: Task | null = null;
  let executions: TaskExecution[] = [];
  let notifications: TaskExecution[] = [];
  let isLoading = true;
  let isExecuting = false;
  let activeTab = 'executions';
  let showDeleteDialog = false;

  async function loadData() {
    isLoading = true;
    try {
      const [taskData, executionsData, notificationsData] = await Promise.all([
        api.getTask(taskId),
        api.getTaskExecutions(taskId),
        api.getTaskNotifications(taskId),
      ]);
      task = taskData;
      executions = executionsData;
      notifications = notificationsData;
    } catch (error) {
      console.error('Failed to load task details:', error);
      toast.error('Failed to load task details');
    } finally {
      isLoading = false;
    }
  }

  onMount(() => {
    loadData();
  });

  async function handleToggle() {
    if (!task) return;
    try {
      await api.updateTask(taskId, { is_active: !task.is_active });
      await loadData();
      toast.success(task.is_active ? 'Task paused' : 'Task activated');
    } catch (error) {
      console.error('Failed to toggle task:', error);
      toast.error('Failed to update task');
    }
  }

  async function handleExecute() {
    isExecuting = true;
    try {
      await api.executeTask(taskId);
      toast.success('Task execution started');
      await loadData();
    } catch (error) {
      console.error('Failed to execute task:', error);
      toast.error('Failed to execute task');
    } finally {
      isExecuting = false;
    }
  }

  async function handleDelete() {
    try {
      await api.deleteTask(taskId);
      toast.success('Task deleted');
      onDeleted();
    } catch (error) {
      console.error('Failed to delete task:', error);
      toast.error('Failed to delete task');
    }
  }
</script>

{#if isLoading}
  <div class="flex items-center justify-center min-h-[400px]">
    <Loader />
  </div>
{:else if !task}
  <div class="text-center py-12">
    <p class="text-muted-foreground mb-4">Task not found</p>
    <Button on:click={onBack}>
      <ArrowLeft class="mr-2 h-4 w-4" />
      Back to Dashboard
    </Button>
  </div>
{:else}
  <div class="space-y-6">
    <div class="flex items-start justify-between">
      <div class="flex items-start gap-4 flex-1">
        <Button variant="ghost" size="icon" on:click={onBack}>
          <ArrowLeft class="h-4 w-4" />
        </Button>
        <div class="flex-1">
          <div class="flex items-center gap-2 mb-2">
            <h1 class="text-3xl font-bold">{task.name}</h1>
            {#if task.condition_met}
              <Badge variant="default">Triggered</Badge>
            {/if}
            {#if !task.is_active}
              <Badge variant="secondary">Paused</Badge>
            {/if}
          </div>
          <p class="text-muted-foreground">{task.search_query}</p>
        </div>
      </div>

      <div class="flex items-center gap-2">
        <Button variant="outline" on:click={handleExecute} disabled={isExecuting}>
          {#if isExecuting}
            <LoaderIcon class="mr-2 h-4 w-4 animate-spin" />
          {:else}
            <Play class="mr-2 h-4 w-4" />
          {/if}
          Run Now
        </Button>

        <Button variant="outline" size="icon" on:click={() => (showDeleteDialog = true)}>
          <Trash2 class="h-4 w-4" />
        </Button>
      </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <Card class="p-4">
        <div class="flex items-center gap-2 text-muted-foreground mb-3">
          <Clock class="h-4 w-4" />
          <p class="text-sm">Schedule</p>
        </div>
        <p class="font-mono text-sm">{task.schedule}</p>
      </Card>

      <Card class="p-4">
        <div class="flex items-center gap-2 text-muted-foreground mb-3">
          <Search class="h-4 w-4" />
          <p class="text-sm">Trigger Condition</p>
        </div>
        <p class="text-sm">{task.condition_description}</p>
      </Card>

      <Card class="p-4">
        <div class="flex items-center gap-2 text-muted-foreground mb-3">
          <Bell class="h-4 w-4" />
          <p class="text-sm">Notification Behavior</p>
        </div>
        <p class="capitalize mb-3 text-sm">{task.notify_behavior.replace('_', ' ')}</p>
        <div class="flex items-center gap-2">
          <Switch checked={task.is_active} on:click={handleToggle} />
          <span class="text-sm text-muted-foreground">
            {task.is_active ? 'Active' : 'Paused'}
          </span>
        </div>
      </Card>
    </div>

    {#if task.last_known_state}
      <Card class="p-4">
        <h3 class="text-lg font-semibold mb-4">Last Known State</h3>
        <div class="text-sm space-y-2">
          {#each Object.entries(task.last_known_state) as [key, value]}
            <div class="flex items-start gap-2">
              <span class="font-medium min-w-[150px]">{key}:</span>
              <span class="text-muted-foreground">
                {typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}
              </span>
            </div>
          {/each}
        </div>
      </Card>
    {/if}

    <div class="space-y-4">
      <div class="flex gap-2 border-b">
        <button
          class="px-4 py-2 text-sm font-medium {activeTab === 'executions' ? 'border-b-2 border-primary' : 'text-muted-foreground'}"
          on:click={() => (activeTab = 'executions')}
        >
          All Executions ({executions.length})
        </button>
        <button
          class="px-4 py-2 text-sm font-medium {activeTab === 'notifications' ? 'border-b-2 border-primary' : 'text-muted-foreground'}"
          on:click={() => (activeTab = 'notifications')}
        >
          Notifications ({notifications.length})
        </button>
        <button
          class="px-4 py-2 text-sm font-medium {activeTab === 'changes' ? 'border-b-2 border-primary' : 'text-muted-foreground'}"
          on:click={() => (activeTab = 'changes')}
        >
          State Changes
        </button>
      </div>

      {#if activeTab === 'executions'}
        <ExecutionTimeline {executions} />
      {:else if activeTab === 'notifications'}
        <ExecutionTimeline executions={notifications} highlightNotifications={true} />
      {:else}
        <StateComparison {executions} />
      {/if}
    </div>
  </div>

  {#if showDeleteDialog}
    <div
      class="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm"
      on:click={() => (showDeleteDialog = false)}
      on:keydown={(e) => e.key === 'Escape' && (showDeleteDialog = false)}
      role="button"
      tabindex="0"
    >
      <div class="fixed left-[50%] top-[50%] z-50 translate-x-[-50%] translate-y-[-50%] w-full max-w-lg">
        <div class="bg-background p-6 shadow-lg rounded-lg border space-y-4">
          <div>
            <h3 class="text-lg font-semibold">Delete Task</h3>
            <p class="text-sm text-muted-foreground mt-2">
              Are you sure you want to delete "{task.name}"? This action cannot be undone. All execution history will be permanently deleted.
            </p>
          </div>
          <div class="flex gap-2 justify-end">
            <Button variant="outline" on:click={() => (showDeleteDialog = false)}>Cancel</Button>
            <Button
              variant="destructive"
              on:click={() => {
                showDeleteDialog = false;
                handleDelete();
              }}
            >
              Delete
            </Button>
          </div>
        </div>
      </div>
    </div>
  {/if}
{/if}
